image: python:3.8-buster

before_script:
  - apt-get update
  - apt-get -y install curl zip
  - pip install -r requirements.txt
  - git config --global user.email "$GITLAB_USER_EMAIL"
  - git config --global user.name "$GITLAB_USER_NAME"

stages:
  - test
  - deploy

test_build:
  stage: test
  script:
  - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
    - test
  allow_failure: true


pages:
  stage: deploy
  only:
    - main
  script:
  - mkdocs build --verbose
  artifacts:
    paths:
    - public
