image: python:3.8-buster

before_script:
  - apt-get update
  - apt-get -y install curl zip
  - pip install -r requirements.txt
  - git config --global user.email "$GITLAB_USER_EMAIL"
  - git config --global user.name "$GITLAB_USER_NAME"

stages:
  - build

build_pages:
  stage: build
  only:
    - main
  script:
    - mkdocs build --verbose
  artifacts:
    paths:
    - public
