image: python:3.8-buster

before_script:
  - apt-get update
  - apt-get -y install curl zip
  - pip install -r requirements.txt
  - git config --global user.email "$GITLAB_USER_EMAIL"
  - git config --global user.name "$GITLAB_USER_NAME"

stages:
  - migrate
  - merge
  - build

update_source:
  stage: migrate
  script:
  - ls
  - 'curl -O --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" https://git.hpcf.nesi.org.nz/api/v4/projects/350/jobs/${REMOTE_JOB_ID}/artifacts/mkdocs.zip'
  #- git clone --branch import https://gitlab-ci-token:${CI_JOB_TOKEN}@git.hpcf.nesi.org.nz/cwal219/mkdocs
  - ls
  #- cd mkdocs
  - unzip -o mkdocs.zip
  - ls
  #- git add --all && git commit -m "$(date)" && git push origin import
  only:
    - triggers
    - import
  artifacts:
    when: always
    paths:  
    - ./*

merge_request:
  stage: merge
  only:
    - import
  script:
  - 'curl -X POST \"${HOST}${CI_PROJECT_ID}/merge_requests\"
    --header \"PRIVATE-TOKEN:${PRIVATE_TOKEN}\"
    --header \"Content-Type: application/json\"
    --data \"{
      \"project_id\": ${CI_PROJECT_ID},
      \"source_branch\": \"${CI_COMMIT_REF_NAME}\",
      \"target_branch\": \"main\",
      \"remove_source_branch\": false,
      \"force_remove_source_branch\": false,
      \"allow_collaboration\": true,
      \"subscribed\" : true,
      \"title\": \"${GITLAB_USER_NAME} merge request for: ${CI_COMMIT_REF_SLUG}\"
    }\"'

build_pages:
  stage: build
  only:
    - main
  script:
    - mkdocs build --verbose
  artifacts:
    paths:
    - public
