image: python:3.8-buster

update:
  stage: .pre
  rules:
  - when: manual
  before_script:
    - pip install -r from_zendesk/requirements.txt
  script:
    - python from_zendesk/refresh_cache.py

migrate:
  stage: .pre
  rules:
    - changes: 
      - "from_zendesk/pandoc/*"
      - "from_zendesk/cache/*"
      - "from_zendesk/convert_docs.py"
  before_script:
    - pip install -r from_zendesk/requirements.txt
  script:
    - python from_zendesk/convert_docs.py

build_pages:
  stage: build
  only:
    - main
  before_script:
    - pip install -r from_zendesk/requirements.txt
  script:
    - mkdocs build --verbose
  artifacts:
    paths:
    - public
