image: python:3.8-buster

before_script:
  - pip install -r requirements.txt

test:
  stage: test
  script:
  - mkdocs build --verbose --site-dir test
  artifacts:
    paths:
    - test
  except:
  - main

pages:
  stage: deploy
  script:
  # - mkdir .public
  # - cp -r * .public
  # - mv .public public
  - mkdocs build --verbose
  # --strict
  artifacts:
    paths:
    - public
  only:
  - main
