image: python:3.8-buster

before_script:
  - apt-get update
  - apt-get -y install curl zip
  - pip install -r requirements.txt

stages:
  - migrate
  - build

update_source:
  stage: migrate
  script:
  - 'curl -O --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" https://git.hpcf.nesi.org.nz/api/v4/projects/350/jobs/${REMOTE_JOB_ID}/artifacts/docs.zip'
  - unzip docs.zip
  - ls -latr
  only:
    - triggers
  artifacts:
    when: always
    paths:  
    - ./*
    - docs.zip
    - docs

build_pages:
  stage: build
  only:
    - main
  script:
    - mkdocs build --verbose
  artifacts:
    paths:
    - public
