image: python:3.8-buster

before_script:
  - apt-get update
  - apt-get -y install curl zip
  - curl https://nodejs.org/dist/v14.15.4/node-v14.15.4-linux-x64.tar.xz -O
  - tar -xf node-v14.15.4-linux-x64.tar.xz
  - ln -s /node-v14.15.4-linux-x64/bin/node /usr/local/bin/node
  - ln -s /node-v14.15.4-linux-x64/bin/npm /usr/local/bin/npm
  - ln -s /node-v14.15.4-linux-x64/bin/npx /usr/local/bin/npx

  - npm install -g markdownlint-cli
  - pip install -r requirements.txt
  - git config --global user.email "$GITLAB_USER_EMAIL"
  - git config --global user.name "$GITLAB_USER_NAME"

stages:
  - update
  - test
  - deploy

update_wordlist:
  stage: update
  artifacts:
    untracked: True
    paths:
      - includes/glossary/*
  script:
  - cd includes/glossary
  - wget https://raw.githubusercontent.com/nesi/nesi-wordlist/main/outputs/Glossary.md
  - wget https://raw.githubusercontent.com/nesi/nesi-wordlist/main/outputs/dictionary.txt
  - wget https://raw.githubusercontent.com/nesi/nesi-wordlist/main/outputs/snippets.md

lint_updated_markdown:
  stage: test
  rules:
    - changes:
      - "**/*.md"
  script:
    - markdownlint $(git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA **/*.md)
  allow_failure: true

lint_all_markdown:
  stage: test
  rules:
    - when: manual
  script:
    - markdownlint "**/*.md" 
  allow_failure: true

test_build:
  stage: test
  script:
  - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
    - test
  allow_failure: true

pages:
  stage: deploy
  only:
    - main
  script:
  - mkdocs build --verbose
  artifacts:
    paths:
    - public
