image: python:3.8-buster

before_script:
  - apt-get update
  - apt-get -y install curl
  - pip install -r requirements.txt

stages:
  - migrate
  - build

update_source:
  stage: migrate
  script:
    - mkdir -P .doc
    - curl --location --output .doc/response.html "https://git.hpcf.nesi.org.nz/cwal219/migratedocs/-/jobs/artifacts/main/download?job=test&job_token=$CI_JOB_TOKEN"
    - ls -latr
    - unzip doc.zip
    - ls
build_pages:
  stage: build
  only:
    - main
  before_script:
    - pip install -r from_zendesk/requirements.txt
  script:
    - mkdocs build --verbose
  artifacts:
    paths:
    - public
