site_name: NeSI Support Center
site_url: https://git.hpcf.nesi.org.nz/cwal219/mkdocs
site_dir: https://git.hpcf.nesi.org.nz/cwal219/mkdocs
repo_url: https://github.com/example/repository/
repo_name: GitLab
site_description: NeSI Support Documentation
nav:
    - 'index.md'
    - 'about.md'
    - 'New Request': https://support.nesi.org.nz/hc/en-gb
theme:
    name: readthedocs
