site_name: NeSI Support Center
site_url: https://git.hpcf.nesi.org.nz/cwal219/mkdocs
site_dir: public
repo_url: https://github.com/example/repository/
repo_name: GitLab
site_description: NeSI Support Documentation
theme:
    name: readthedocs
    locale: en
plugins:
    - search
nav:
    - Getting_Started
    - Scientific_Computing
    - Storage
    - General
