site_name: NeSI Support Center
site_url: https://git.hpcf.nesi.org.nz/cwal219/mkdocs
site_dir: public
repo_url: https://github.com/example/repository/
repo_name: GitLab
site_description: NeSI Support Documentation
theme:
    name: readthedocs
    locale: en
plugins:
    - search
nav:
    - Getting_Started:
        - Release_Notes_my.nesi.org.nz:
            - my.nesi.org.nz_release_notes_v2.2.0
            - my.nesi.org.nz_release_notes_v2.1.0
            - my.nesi.org.nz_release_notes_v2.0.3
            - my.nesi.org.nz_release_notes_v2.0.1
        - Accounts,_Projects_and_Allocations:
            - Creating_a_NeSI_Account_Profile
            - Applying_for_a_NeSI_project
            - Applying_to_join_a_NeSI_project
            - What_is_an_allocation?
            - Project_Extensions_and_New_Allocations_on_Existing_Projects
        - Accessing_the_HPCs:
            - Setting_Up_and_Resetting_Your_Password
            - Setting_Up_Two-Factor_Authentication
            - Choosing_and_Configuring_Software_for_Connecting_to_the_Clusters
            - Port_Forwarding
        - First_Steps:
            - Moving_files_to_and_from_the_cluster
            - Submitting_your_first_job
            - Parallel_Execution
            - Job_Scaling_-_Ascertaining_job_dimensions
            - OpenMP_Scaling_Example
            - MPI_Scaling_Example
            - Finding_Job_Efficiency
            - The_HPC_environment_
        - Getting_Help:
            - Job_efficiency_review
            - User_support
            - Can_I_attend_an_Introductory_Workshop?
            - Consultancy
            - System_status
        - Cheat_Sheets:
            - Unix_Shell:_Reference_Sheet
            - Slurm:_Reference_Sheet
            - Git:_Reference_Sheet
        - my.nesi.org.nz:
        - Logging_in_to_my.nesi.org.nz
        - Navigating_the_my.nesi.org.nz_web_interface
        - The_NeSI_Project_Request_Form
        - User_Feedback_Portal_for_my.nesi.org.nz
    - Scientific_Computing:
        - Release_Notes_jupyter.nesi.org.nz:
            - jupyter.nesi.org.nz_release_notes_12-05-2021
        - Interactive_computing_using_Jupyter:
            - Jupyter_on_NeSI
            - RStudio_via_Jupyter
            - Virtual_Desktop_via_Jupyter_on_NeSI
        - The_NeSI_High_Performance_Computers:
            - Overview
            - Total_HPC_Resources_Available
            - Mahuika
            - "M\u0101ui"
            - "M\u0101ui_Ancillary_Nodes"
        - Supported_Applications:
            - ABAQUS
            - ANSYS
            - BLAST
            - CESM
            - COMSOL
            - Delft3D
            - FDS
            - Gaussian
            - GROMACS
            - Java
            - Julia
            - JupyterLab
            - Keras
            - Lambda_Stack
            - MAKER
            - MATLAB
            - OpenFOAM
            - OpenSees
            - ORCA
            - ParaView
            - Python
            - R
            - RAxML
            - Relion
            - Singularity
            - Software_Installation_Request
            - Supernova
            - Synda
            - TensorFlow_on_CPUs
            - TensorFlow_on_GPUs
        - "Running_Jobs_on_M\u0101ui_and_Mahuika":
            - GPU_use_on_NeSI
            - Job_Checkpointing
            - Slurm_Interactive_Sessions
            - Fair_Share
            - Job_prioritisation
            - Mahuika_Slurm_Partitions
            - "M\u0101ui_Slurm_Partitions"
            - SLURM:_Best_Practice
            - Hyperthreading
            - NetCDF_-_HDF5_file_locking
            - Checksums
        - Profiling_and_Debugging:
            - Slurm_Native_Profiling
            - Profiler:_ARM_MAP
            - Debugging
        - HPC_Software_Environment:
            - OpenMP_settings
            - Offloading_to_GPU_with_OpenMP_
            - Offloading_to_GPU_with_OpenACC_using_the_Cray_compiler
            - NVIDIA_GPU_Containers
            - Configuring_Dask-MPI_jobs
            - Software_Version_Management
            - Thread_Placement_and_Thread_Affinity
            - NICE_DCV_Setup
            - Visualisation_software
            - Finding_Software
            - Installing_(Third_Party)_applications
            - Compiling_software_on_Mahuika
            - "Compiling_software_on_M\u0101ui"
            - Programming_environment_differences_and_similarities_of_Maui_and_Mahuika
        - Terminal_Setup:
            - Standard_Terminal_Setup
            - Ubuntu_LTS_terminal_(Windows_10)
            - MobaXterm_Setup_(Windows)
            - WinSCP-PuTTY_Setup_(Windows)
            - X11_on_NeSI
            - Windows_Subsystem_for_Linux_(WSL)
        - Manuals,_User_Guides_and_Training:
        - '''Quick_Tips''_Training_Webinars'
        - Manuals
        - XC50_Aries_Network_Architecture
    - Storage:
        - Release_Notes_Long-Term_Storage:
            - Long-term_Storage_-_Nearline_release_notes_v1.1.0.20
            - Long-term_Storage_-_Nearline_release_notes_v1.1.0.19
            - Long-term_Storage_-_Nearline_release_notes_v1.1.0.18
            - Long-Term_Storage_-_Nearline_release_notes__v1.1.0.14
        - File_Systems_and_Quotas:
            - NeSI_File_Systems_and_Quotas
            - Automatic_cleaning_of_nobackup_file_system
            - File_permissions_and_groups
            - I-O_Performance_Considerations
        - Data_Recovery:
            - File_Recovery
        - Data_Transfer_Services:
            - Data_Transfer_using_Globus
            - Initial_Globus_Sign-Up,_and_your_Globus_Identities
            - Globus_Paths,_Permissions,_Storage_Allocation
            - Personal_Globus_Endpoint_Configuration
            - New_Zealand_Data_Transfer_Platform
            - Globus_endpoint_activation
            - Download_and_share_CMIP6_data_(for_NIWA_researchers)
        - Long-Term_Storage:
        - Long-Term_Storage_Service
        - Preparing_small_files_for_migration_to_Nearline_storage
        - Verifying_uploads_to_Nearline_storage
    - General:
        - Announcements:
            - New_capabilities_for_Machine_Learning_and_GPU_pricing_updates
            - University_of_Auckland_-_ANSYS_users
            - Accessing_NeSI_Support_during_the_holiday_break
            - "Improvements_to_Fair_Share_job_prioritisation_on_M\u0101ui"
            - Update:_Automatic_cleaning_of_nobackup_file_system_-_all_new_projects_will_be_automatically_enrolled
            - Accessing_NeSI_platforms_and_support_during_COVID-19_Alert_Level_4
            - Post_outage_bulletin_-_24-02-20
            - Clean-up_of_Pan_migration_directories_from_2018
            - Improving_your_NeSI_login_experience
            - Important_changes_to_storing_data_on_NeSI_-_expiry_of_data_on_'nobackup'_filesystem
            - MobaXterm_Crashes_on_NeSI_clusters_(Update_-_Resolved)
            - Online_training_(Oct_09):_Getting_started_with_NeSI_HPC_Platforms
            - Online_training_(Sept_11):_Sharing_data_&_setting_up_groups_using_Globus
            - Online_Training_(15_July)_-_Python_Profiling_on_NeSI
            - Training_workshop_(Christchurch_-_04_Sept):_Python_Code_Optimisation_on_NeSI
            - NeSI_launches_national_high-speed_Data_Transfer_platform
            - Access_to_NeSI_HPCs_interrupted_(unplanned_outage)_12-03-2019
            - Outcomes_of_maintenance_conducted_12-02-2019_-_13-02-2019
            - 2018_Platforms_Migration_Survey
            - Transitioning_to_Maui_-_Everything_you_need_to_Know
            - Transitioning_to_Mahuika_-_Everything_you_need_to_Know
        - FAQs:
            - Can_I_change_my_time_zone_to_New_Zealand_time?
            - Can_I_use_SSHFS_to_mount_the_cluster_filesystem_on_my_local_machine?
            - Converting_from_Windows-style_to_UNIX-style_line_endings
            - How_can_I_give_read-only_team_members_access_to_my_files?
            - How_can_I_let_my_fellow_project_team_members_read_or_write_my_files?
            - How_can_I_see_how_busy_the_cluster_is?
            - How_can_I_view_images_generated_on_the_cluster?
            - How_do_I_request_memory?
            - How_to_replace_my_2FA_token
            - How_to_submit_feedback_or_a_new_idea_using_a_product_portal?
            - I_have_not_scanned_the_2FA_QR_code
            - I've_run_out_of_storage_space
            - Logging_in_to_the_HPCs
            - Login_Troubleshooting
            - "Mahuika_-_M\u0101ui_Differences"
            - Password_Expiry
            - "Skylake_warning_message_on_M\u0101ui"
            - Two_Factor_Authentication_FAQ
            - What_are_my_.bashrc_&_.bash_profile_for?
            - What_does_"oom-kill"_mean?
            - What_is_a_'.core'_file?
            - What_software_environments_on_NeSI_are_optimised_for_Machine_Learning_and_data_science?
            - Why_am_I_seeing_'Account_is_not_ready'?
            - Why_can't_I_log_in_using_MobaXTerm?
            - Why_does_my_program_crash?
            - Why_is_my_job_taking_a_long_time_to_start?
        - Release_Notes:
            - About_the_Release_Notes_section
        - NeSI_Policies:
        - Acceptable_Use_Policy
        - Access_Policy
        - Account_Requests_for_non-Tuakiri_Members
        - Acknowledgement,_Citation_and_Publication
        - Allocation_classes
        - How_we_review_applications
        - Institutional_allocations
        - Merit_allocations
        - NeSI_Application_Support_Model
        - NeSI_Licence_Policy
        - NeSI_Password_Policy
        - Postgraduate_allocations
        - Proposal_Development_allocations
