hooks:
  - custom_hooks.py
markdown_extensions:
  - toc:
      baselevel: 1
      permalink: true
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - abbr
  - tables
  - neoteroi.cards
  - neoteroi.timeline
  - pymdownx.snippets:
      auto_append:
        - assets/glossary/snippets.md
not_in_nav: |
    assets/.*
plugins:
  - search
      # - spellcheck:
    #     known_words: ../includes/dictionary.txt
    #     ignore_code: yes
    #     min_length: 3
    #     max_capital: 1
    #     allow_unicode: yes
  - tags: null
  - git-authors
  - macros:
      include_dir: docs/assets
repo_name: GitLab
repo_url: https://github.com/example/repository/
site_description: NeSI Support Documentation
site_dir: public
site_name: NeSI Support Center
site_url: https://github.com/nesi/support-docs-concept
extra_css:
  - assets/stylesheets/neoteroi-mkdocs.css
  - assets/stylesheets/footer.css
  - assets/stylesheets/supportedApplications.css
extra_javascript:
  - https://code.jquery.com/jquery-3.7.0.min.js
  - javascripts/supportedApplications.js
theme:
  custom_dir: overrides
  favicon: assets/icons/favicon.ico
  features:
    - navigation.indexes
    - navigation.top
    - content.code.copy
  language: en
  logo: assets/icons/logo.svg
  name: material
  palette:
    - primary: grey
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - primary: black
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    # on_post_build: "custom_hooks:check_links" # This doesn't work very well.
    #on_post_build: ":lint"
