site_name: NeSI Support Center
site_url: https://git.hpcf.nesi.org.nz/cwal219/mkdocs
site_dir: public
repo_url: https://github.com/example/repository/
repo_name: GitLab
site_description: NeSI Support Documentation
# theme:
#     name: bootstrap4
#     locale: en
#     custom_dir: 'theme/'
theme:
    name: material
# theme:
#     name: null
#     custom_dir: nesi_theme/

markdown_extensions:
    - toc:
        permalink: True
        baselevel: 1
        toc_depth: 4
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true 
plugins:
    - search
    - spellcheck:
        known_words: ../dictionary.txt
        ignore_code: yes
        min_length: 3
        max_capital: 1
        allow_unicode: no
    - mkdocs-simple-hooks:
        hooks:
extra_javascript:
  - JavaScripts/se-v2.js
            # on_post_build: "custom_hooks:test"
    # - section-index

