site_name: NeSI Support Center
site_url: https://git.hpcf.nesi.org.nz/cwal219/mkdocs
site_dir: public
repo_url: https://github.com/example/repository/
repo_name: GitLab
site_description: NeSI Support Documentation
theme:
    name: material
    features:
    #- navigation.indexes    # Allow navigation to secion pages
    - navigation.top        # Adds 'return to top' button


# theme:
#     name: null
#     custom_dir: nesi_theme/

markdown_extensions:
    - toc:
        permalink: True
        baselevel: 1
        toc_depth: 3
    - pymdownx.superfences
    - pymdownx.highlight        # code blocks
    - pymdownx.inlinehilite     # code blocks  
    - pymdownx.tabbed:
        alternate_style: true 
    - abbr
    - pymdownx.snippets:
      auto_append:
        - includes/snippets.md
plugins:
    - search
    - spellcheck:
        known_words: ../includes/dictionary.txt
        ignore_code: yes
        min_length: 3
        max_capital: 1
        allow_unicode: yes
    - mkdocs-simple-hooks:
        hooks: 
            # on_post_build: "custom_hooks:check_links" # This doesn't work very well.
            #on_post_build: "custom_hooks:lint"


#extra_javascript:
#  - JavaScripts/se-v2.js # js for statuspage thingie
    # - section-index

