name: Checks
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      fileList:
        description: 'Files to Lint'
        required: true
        type: string
jobs:
  proselint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install proselint
      - run: |
          shopt -s globstar extglob
          proselint ${{inputs.fileList}}
  mdlint:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - run: npm install markdownlint -g
       - run: |
          shopt -s globstar extglob
          npm run markdownlint ${{inputs.fileList}}

