name: Checks
on:
  workflow_dispatch:
    inputs:
      fileList:
          description: 'Files to Lint'
          required: true
          type: string
  workflow_call:
    inputs:
      fileList:
        description: 'Files to Lint'
        required: true
        type: string
jobs:
  proselint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install proselint
      - run: |
          echo "Running ProseLint"
          shopt -s globstar extglob
          echo ${{inputs.fileList}}
          python3 checks/run_proselint.py ${{inputs.fileList}} 
  mdlint:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - run: npm install -g markdownlint-cli
       - run: |
          echo "Running MarkdownLint"
          shopt -s globstar extglob
          echo ${{inputs.fileList}}
          markdownlint --disable MD033 --json ${{inputs.fileList}} 2>&1 | checks/parse_markdownlint.py

