name: Checks
on:
  workflow_dispatch:
    inputs:
      fileList:
          description: 'Files to Lint'
          required: true
          type: string
  workflow_call:
    inputs:
      fileList:
        description: 'Files to Lint'
        required: true
        type: string
jobs:
  proselint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install proselint
      - run: |
          shopt -s globstar extglob
          python3 checks/run_proselint.py ${{inputs.fileList}} 
  mdlint:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - run: npm install -g markdownlint-cli
       - run: |
          shopt -s globstar extglob
          markdownlint -j ${{inputs.fileList}}

