name: Checks
on:
  workflow_dispatch:
    inputs:
      fileList:
          description: 'Files to Lint'
          required: true
          type: string
  workflow_call:
    inputs:
      fileList:
        description: 'Files to Lint'
        required: true
        type: string
jobs:
  proselint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install proselint
      - run: |
          shopt -s globstar extglob
          proselint ${{inputs.fileList}}
  mdlint:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-node@v3
       - run: npm --loglevel verbose install markdownlint  
       - run: |
          ls /usr/local/bin
          shopt -s globstar extglob
          markdownlint ${{inputs.fileList}}

