name: Check Changed Files
on:
  push:
    paths:
      - docs/**/*.md
jobs:
  runChecks:
    uses: ./.github/workflows/checks.yml
    with:
      fileList: "$(git diff-tree --no-commit-id --name-only -r $GITHUB_SHA **/*.md)" 
