name: Deploy to gh-pages 
on: 
 workflow_dispatch:
  inputs:
    dry-run:
      type: boolean
      description: If true, will build but deploy to gh-pages-test.
      default: true
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: mkdocs gh-deploy $( if ${{ github.event.inputs.dry-run }}; then echo "-b gh-pages-test --verbose";fi ) --force
