name: Fetch Remote Assets 
on: workflow_dispatch
# permissions:
#  contents: write
env:
  MODULES_LIST: "https://raw.githubusercontent.com/nesi/modules-list/main/module-list.json"
  GLOSSARY: "https://raw.githubusercontent.com/nesi/nesi-wordlist/main/outputs/Glossary.md"
  DICTIONARY: "https://raw.githubusercontent.com/nesi/nesi-wordlist/main/outputs/dictionary.txt"
  SNIPPETS: "https://raw.githubusercontent.com/nesi/nesi-wordlist/main/outputs/snippets.md"
  BRANCH_NAME: "new-assets"
jobs:
  fetch-includes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git config --global user.name "${GITHUB_ACTOR}"
      - run: git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: wget -P includes $MODULES_LIST
      - run: git status
      - run: git add --all
      - run: git commit -m "update module list"
      - run: git checkout -b $BRANCH_NAME
      - run: git push origin $BRANCH_NAME
  fetch-dictionary:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - run: git config --global user.name "${GITHUB_ACTOR}"
      - run: git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: wget -P docs $GLOSSARY
      - run: wget -P includes $DICTIONARY
      - run: wget -P includes $SNIPPETS
      - run: git status
      - run: git add --all
      - run: git commit -m "update module list"
      - run: git checkout -b $BRANCH_NAME
      - run: git push origin $BRANCH_NAME
  open-pr:
      runs-on: ubuntu-latest
      steps:
      - run: git config --global user.name "${GITHUB_ACTOR}"
      - run: git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: gh pr create -B main -H $BRANCH_NAME --title 'Update remote assets' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
