name: Fetch Remote Assets 
on: workflow_dispatch
# permissions:
#  contents: write
env:
  MODULES_LIST: "https://raw.githubusercontent.com/nesi/modules-list/main/module-list.json"
jobs:
  fetch-includes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git config --global user.name "${GITHUB_ACTOR}"
      - run: git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: wget -P includes $MODULES_LIST
      - run: git status
      - run: git add --all
      - run: git commit -m "update module list"
      - run: git checkout -b $GITHUB_WORKFLOW_SHA
      - run: git push origin $GITHUB_WORKFLOW_SHA
