on:
  push:
    branches:
      - main
    paths:
      - docs/*.md
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: proselint "$(git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA **/*.md)"
      - run: markdownlint "$(git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA **/*.md"
